name: OpenInv
main: com.lishid.openinv.OpenInv
version: 2.2.8
author: lishid
description: >
             This plugin allows you to open a player's inventory as a chest and interact with it in real time.
commands:
  openinv:
    aliases: [oi, inv, open]
    description: Open a player's inventory
    usage: |
           /<command> - Open last person's inventory
           /<command> <Player> - Open a player's inventory
  openender:
    aliases: [oe]
    description: Opens the enderchest of a player
    usage: |
           /<command> <Player> - Opens a player's enderchest
  searchinv:
    aliases: [si]
    description: Search and list players having a specific item
    usage: |
           /<command> <Item> [MinAmount] - Item can be the Item ID or the CraftBukkit Item Name, MinAmount is the minimum amount to be considered.
  toggleopeninv:
    aliases: [toi, toggleoi, toggleinv]
    description: Toggle item openinv function
    usage: |
           /<command> [Check] - Checks whether item openinv is enabled
  silentchest:
    aliases: [sc, silent]
    description: Toggle silent chest function, which hides the animation of a chest when opened or closed, and suppresses the sound.
    usage: |
           /<command> [Check] - Checks whether silent chest is enabled
  anychest:
    aliases: [ac]
    description: Toggle anychest function, which allows opening of blocked chests.
    usage: |
           /<command> [Check] - Checks whether anychest is enabled
